- name: Create the repository for Jenkins
  copy: src=jenkins.repo dest=/etc/yum.repos.d/jenkins.repo
  tags: jenkins

- name: Added Jenkins RPM Key
  rpm_key: state=present key=http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key
  tags: jenkins

- name: Jenkins Install
  yum: pkg=jenkins state=installed
  notify:
    - running jenkins
  tags: jenkins

- name: Exists File Iptables
  shell:
    if [ -e /etc/sysconfig/iptables ]; then
      echo "1";
    else
      echo "0";
    fi
  register: result
  changed_when: result.stdout.find('1') == 1

- name: Chenged Iptables If Exists File Iptables
  template: src=iptables.j2 dest=/etc/sysconfig/iptables
  when: result.stdout.find('1') != 1

- name: started jenkins
  service: name=jenkins state=started

- name: iptables restart
  service: name=iptables state=restarted
  when: result.stdout.find('1') != 1
