- hosts: all
  sudo: yes
  roles:
    - { role: sshd }
    - { role: yum/epel }
- hosts: LOCAL
  sudo: yes
  roles:
    - { role: yum/remi }
    - { role: yum/rpmforge }
    - { role: vim-enhanced/install }
    - { role: vim-enhanced/plugins/neobundle }
    - { role: ruby/rbenv }
    - { role: ruby/ruby-build }
    - { role: ruby/gem/bundle }
    - { role: ruby/bundle }
    - { role: git }
    - { role: java/openjdk }
    - { role: jenkins/install }
    - { role: jenkins/plugins/rbenv }
    - { role: jenkins/plugins/yammer }

- hosts: LOCAL
  sudo: yes
  roles:
